### ISSUE TITLE
So many errors!

### ISSUE THREAD

**Issue by twilson90** [FuzzyWuzzie/LuxeLights#1]
I'd really like to get this example running to help me with my own project, but as the README says it's become outdated and now there's a litany of errors. As a newcomer I'm not familiar with the old outdated API so I can't fix this easily myself.

**Comment by hamaluik** [comment]
I would love to keep this up to date, but unfortunately I'm too busy with other more pressing things right now, so this likely won't be updated anytime soon.

In the meantime, I'll happily accept pull requests and if you ask nicely on https://gitter.im/snowkit/public I'm sure the fine folks there will be able to help you sort things out.
